import type { MediaByteSource } from "./bytes";

/**
 * Media-object repository port: the database-backed home for stored product
 * media.
 *
 * Structural contract shared by the local better-sqlite3 implementation and the
 * Cloudflare D1 implementation, mirroring the other domain repositories
 * (products, cart, audit). Every method is async so the same interface drives
 * both drivers (better-sqlite3 is synchronous; D1 is promise-based). This
 * module is deliberately dependency-free: it never imports a database client,
 * so edge/API runtimes can import the contract without pulling in the Node-only
 * SQLite stack.
 *
 * What this port is, and is not:
 *
 * - It is **byte storage with metadata**: one immutable object per row, addressed
 *   by an opaque server-generated `storageKey`, carrying the verified content
 *   type, the exact byte length and the bytes themselves.
 * - It is **not** the presentation record. Which products an object belongs to
 *   lives in `product_media`, and how an image is displayed (URL, ordering,
 *   primary flag) lives in `product_images`. Keeping those apart is what lets
 *   the public catalog read one URL column whether the bytes behind it live in
 *   R2, on local disk, or in D1.
 *
 * Objects are immutable once written. There is deliberately no `update`: a
 * changed image is a new object under a new key, so a reader can never observe a
 * half-written object and the delete/replace path never has to reason about
 * partially updated bytes.
 *
 * Identity is server-generated, never accepted from client input. `id` is
 * generated by the driver (UUIDv7, the repository-wide id format) and
 * `storageKey` is generated by the caller's server-side key scheme, which is why
 * `create` surfaces a UNIQUE violation as a thrown error rather than as a
 * conflict result: unlike a user-chosen product slug, a collision here is a
 * programming fault and never a request the client can fix.
 */

/** A persisted media-object row, mirroring the `media_objects` table. */
export interface MediaObjectRecord {
  id: string;
  /** The key the storage driver addresses this object by. */
  storageKey: string;
  /** The verified content type of {@link MediaObjectRecord.bytes}. */
  contentType: string;
  /**
   * The object's length in bytes. Always equal to `bytes.byteLength`: the
   * `media_objects_byte_size_matches_bytes` CHECK enforces it in SQL, so a
   * driver that disagreed with itself could not write the row at all.
   */
  byteSize: number;
  /**
   * The stored bytes as a canonical `Uint8Array`.
   *
   * Deliberately *not* a `Buffer`: the D1 driver runs in the Worker, where
   * `Buffer` does not exist, so the port's byte type is the one container both
   * runtimes share. The `MediaStorage` port, which serves a single object to
   * HTTP, keeps using `ArrayBuffer` — the conversion between the two is a
   * `.buffer` away and happens at the driver edge.
   */
  bytes: Uint8Array;
  createdAt: Date;
  /** Content hash of the bytes, or `null` when it was not computed. */
  checksum: string | null;
}

/**
 * Everything required to store one object.
 *
 * `bytes` is accepted as an `ArrayBuffer` or any typed array so the value that
 * arrived from an HTTP body, an R2 read or a filesystem read can be handed
 * straight over; the drivers normalize it to a `Uint8Array` copy. `byteSize` is
 * **not** an input: it is derived from the bytes, so a caller cannot record a
 * size that disagrees with what it stored.
 */
export interface CreateMediaObjectInput {
  /** Opaque, server-generated key, unique across all objects. */
  storageKey: string;
  /** The verified content type — sniffed from the bytes, never client-declared. */
  contentType: string;
  /** The object's bytes. */
  bytes: MediaByteSource;
  /** Optional content hash; omitted means `null` in the stored row. */
  checksum?: string | null;
}

export interface MediaObjectRepository {
  /**
   * Store one new object and return the persisted row. The id and
   * `createdAt` are generated by the driver; a duplicate `storageKey` throws
   * (see the module comment for why a collision is not a result value).
   */
  create(input: CreateMediaObjectInput): Promise<MediaObjectRecord>;
  /** Resolve one object by id, or `null` when no such object exists. */
  findById(id: string): Promise<MediaObjectRecord | null>;
  /**
   * Resolve one object by its storage key, or `null`. Exact rather than a scan:
   * `media_objects.storage_key` is UNIQUE, and this is the lookup a read or
   * replace path needs when it only knows the key it is about to serve.
   */
  findByStorageKey(storageKey: string): Promise<MediaObjectRecord | null>;
  /**
   * Delete one object by id. Returns `true` when a row was removed and `false`
   * when the object did not exist, so a caller can tell a real delete from a
   * no-op without a second read. Deleting an object attached to products
   * removes its `product_media` rows by `ON DELETE CASCADE`.
   */
  delete(id: string): Promise<boolean>;
}
