import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text, unique } from "drizzle-orm/sqlite-core";
import { createdAtColumn, idColumn } from "./_common";
import { users } from "./identities";

/**
 * Server-side authentication sessions.
 *
 * One row per opaque login session. Only the SHA-256 `token_hash` of the raw
 * token is persisted: the raw session token is generated by the auth service,
 * returned to the client as an HttpOnly cookie, and never stored anywhere. The
 * CSRF synchronizer token is stored alongside the session so mutating requests
 * can be verified without a second cookie.
 *
 * Sessions are ephemeral. Deleting a user cascades to their sessions
 * (`ON DELETE CASCADE`), expired rows are purged by the repository, and nothing
 * here implements policy — the 30-day lifetime is supplied later by the auth
 * service. The hash format is fixed by the security primitives (SHA-256 digest
 * over 32 random bytes, base64url, no padding), so both hash columns enforce a
 * 43-character length with an explicit CHECK.
 */
export const authSessions = sqliteTable("auth_sessions", {
  id: idColumn(),
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  tokenHash: text("token_hash").notNull(),
  csrfToken: text("csrf_token").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  createdAt: createdAtColumn(),
  lastUsedAt: integer("last_used_at", { mode: "timestamp_ms" }),
}, (table) => [
  unique("auth_sessions_token_hash_unique").on(table.tokenHash),
  index("auth_sessions_user_id_idx").on(table.userId),
  index("auth_sessions_expires_at_idx").on(table.expiresAt),
  check("auth_sessions_token_hash_length", sql`length(${table.tokenHash}) = 43`),
  check("auth_sessions_csrf_token_length", sql`length(${table.csrfToken}) = 43`),
]);